### ISSUE TITLE
Please create installer/executable for windows

### ISSUE THREAD

**Issue by anjanb** [fiatjaf/jqview#1]
Windows 10 executable please. Thank you.

**Comment by fiatjaf** [comment]
I don't know how to do it! Maybe someone with a Windows computer can generate these binaries. Normal cross-compilation doesn't work because it requires CGO and libmesa or other things I don't understand.

**Comment by fiatjaf** [comment]
Done here: https://github.com/fiatjaf/jqview/releases/tag/v2
